### ISSUE TITLE
`nope` or `run`

### ISSUE THREAD

**Issue by durban** [SystemFw/blog#2]
In [Programs as Values V.](https://systemfw.org/posts/programs-as-values-V.html) there is an example:
```
sealed trait In {
  def nope: String
  ...
object In {
  val readLine: In
  ...
```
But then in the next line it is run by:
```
val out: Boolean = readLine.run.length > 10
```
Maybe that should be `readLine.nope.length`?

**Comment by SystemFw** [comment]
Thanks for spotting this! I'll fix it
